language: node_js

node_js:
  - "0.10"

# http://about.travis-ci.org/blog/2013-11-29-postgresql-92-93-now-available/
addons:
  postgresql: "9.3"

before_install:
 - createdb template_postgis
 - psql -c "CREATE EXTENSION postgis" template_postgis

install:
 - npm install

before_script:
 - npm install mocha
 - npm ls

script:
 - node ./test/fixtures-oauth/mapbox.js &
 - node index.js --mapboxauth="http://localhost:3001" --db="./test/fixtures-oauth/test.db" &
 - sleep 10
 - ./node_modules/.bin/mocha-phantomjs "http://localhost:3000/style?id=tmstyle:///tmp-1371d3fb&test=true"
 - sleep 10
 - npm test

